version: '3.8'

services:
  bilinote:
    build: .
    container_name: bilinote
    ports:
      - "3015:80"
    volumes:
      - ./www:/var/www/html
      - ./uploads:/var/www/uploads
    env_file:
      - ./www/.env
    command: >
      bash -c "mkdir -p /var/www/uploads/videos && chmod 777 /var/www/uploads/videos && apache2-foreground"
    restart: unless-stopped
